/* Generated by a program written by John Boyland */
#include <stdio.h>
#include "aps-tree.h"
#include "aps-tree-dump.h"
#include "aps-tree-dump.handcode.i"

void dump_lisp_Signature(Signature _node){
  int _l = tnode_line_number(_node);
  switch (Signature_KEY(_node)) {
    default: fatal_error("dump_lisp_Signature crashes");
    case KEYmult_sig:
      printf("%c(mult_sig #%d!",10,_l);
dump_lisp_Signature(mult_sig_sig1(_node));
dump_lisp_Signature(mult_sig_sig2(_node));
      printf(")");
      break;
    case KEYfixed_sig:
      printf("%c(fixed_sig #%d!",10,_l);
dump_lisp_Types(fixed_sig_types(_node));
      printf(")");
      break;
    case KEYno_sig:
      printf("%c(no_sig #%d!",10,_l);
      printf(")");
      break;
    case KEYsig_inst:
      printf("%c(sig_inst #%d!",10,_l);
dump_lisp_Boolean(sig_inst_is_input(_node));
dump_lisp_Boolean(sig_inst_is_var(_node));
dump_lisp_Class(sig_inst_class(_node));
dump_lisp_TypeActuals(sig_inst_actuals(_node));
      printf(")");
      break;
    case KEYsig_use:
      printf("%c(sig_use #%d!",10,_l);
dump_lisp_Use(sig_use_use(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Type(Type _node){
  int _l = tnode_line_number(_node);
  switch (Type_KEY(_node)) {
    default: fatal_error("dump_lisp_Type crashes");
    case KEYprivate_type:
      printf("%c(private_type #%d!",10,_l);
dump_lisp_Type(private_type_rep(_node));
      printf(")");
      break;
    case KEYfunction_type:
      printf("%c(function_type #%d!",10,_l);
dump_lisp_Declarations(function_type_formals(_node));
dump_lisp_Declarations(function_type_return_values(_node));
      printf(")");
      break;
    case KEYremote_type:
      printf("%c(remote_type #%d!",10,_l);
dump_lisp_Type(remote_type_nodetype(_node));
      printf(")");
      break;
    case KEYno_type:
      printf("%c(no_type #%d!",10,_l);
      printf(")");
      break;
    case KEYtype_inst:
      printf("%c(type_inst #%d!",10,_l);
dump_lisp_Module(type_inst_module(_node));
dump_lisp_TypeActuals(type_inst_type_actuals(_node));
dump_lisp_Actuals(type_inst_actuals(_node));
      printf(")");
      break;
    case KEYtype_use:
      printf("%c(type_use #%d!",10,_l);
dump_lisp_Use(type_use_use(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Expression(Expression _node){
  int _l = tnode_line_number(_node);
  switch (Expression_KEY(_node)) {
    default: fatal_error("dump_lisp_Expression crashes");
    case KEYcontrolled:
      printf("%c(controlled #%d!",10,_l);
dump_lisp_Expression(controlled_expr(_node));
dump_lisp_Declaration(controlled_formal(_node));
dump_lisp_Expression(controlled_set(_node));
      printf(")");
      break;
    case KEYguarded:
      printf("%c(guarded #%d!",10,_l);
dump_lisp_Expression(guarded_expr(_node));
dump_lisp_Expression(guarded_cond(_node));
      printf(")");
      break;
    case KEYrepeat:
      printf("%c(repeat #%d!",10,_l);
dump_lisp_Expression(repeat_expr(_node));
      printf(")");
      break;
    case KEYpattern_value:
      printf("%c(pattern_value #%d!",10,_l);
dump_lisp_Pattern(pattern_value_p(_node));
      printf(")");
      break;
    case KEYtype_value:
      printf("%c(type_value #%d!",10,_l);
dump_lisp_Type(type_value_T(_node));
      printf(")");
      break;
    case KEYsignature_value:
      printf("%c(signature_value #%d!",10,_l);
dump_lisp_Signature(signature_value_s(_node));
      printf(")");
      break;
    case KEYmodule_value:
      printf("%c(module_value #%d!",10,_l);
dump_lisp_Module(module_value_m(_node));
      printf(")");
      break;
    case KEYclass_value:
      printf("%c(class_value #%d!",10,_l);
dump_lisp_Class(class_value_c(_node));
      printf(")");
      break;
    case KEYempty:
      printf("%c(empty #%d!",10,_l);
      printf(")");
      break;
    case KEYappend:
      printf("%c(append #%d!",10,_l);
dump_lisp_Expression(append_s1(_node));
dump_lisp_Expression(append_s2(_node));
      printf(")");
      break;
    case KEYfuncall:
      printf("%c(funcall #%d!",10,_l);
dump_lisp_Expression(funcall_f(_node));
dump_lisp_Actuals(funcall_actuals(_node));
      printf(")");
      break;
    case KEYno_expr:
      printf("%c(no_expr #%d!",10,_l);
      printf(")");
      break;
    case KEYundefined:
      printf("%c(undefined #%d!",10,_l);
      printf(")");
      break;
    case KEYchar_const:
      printf("%c(char_const #%d!",10,_l);
dump_lisp_String(char_const_token(_node));
      printf(")");
      break;
    case KEYstring_const:
      printf("%c(string_const #%d!",10,_l);
dump_lisp_String(string_const_token(_node));
      printf(")");
      break;
    case KEYreal_const:
      printf("%c(real_const #%d!",10,_l);
dump_lisp_String(real_const_token(_node));
      printf(")");
      break;
    case KEYinteger_const:
      printf("%c(integer_const #%d!",10,_l);
dump_lisp_String(integer_const_token(_node));
      printf(")");
      break;
    case KEYtyped_value:
      printf("%c(typed_value #%d!",10,_l);
dump_lisp_Expression(typed_value_expr(_node));
dump_lisp_Type(typed_value_type(_node));
      printf(")");
      break;
    case KEYvalue_use:
      printf("%c(value_use #%d!",10,_l);
dump_lisp_Use(value_use_use(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Pattern(Pattern _node){
  int _l = tnode_line_number(_node);
  switch (Pattern_KEY(_node)) {
    default: fatal_error("dump_lisp_Pattern crashes");
    case KEYpattern_function:
      printf("%c(pattern_function #%d!",10,_l);
dump_lisp_Declarations(pattern_function_formals(_node));
dump_lisp_Pattern(pattern_function_body(_node));
      printf(")");
      break;
    case KEYhole:
      printf("%c(hole #%d!",10,_l);
      printf(")");
      break;
    case KEYcondition:
      printf("%c(condition #%d!",10,_l);
dump_lisp_Expression(condition_e(_node));
      printf(")");
      break;
    case KEYpattern_var:
      printf("%c(pattern_var #%d!",10,_l);
dump_lisp_Declaration(pattern_var_formal(_node));
      printf(")");
      break;
    case KEYand_pattern:
      printf("%c(and_pattern #%d!",10,_l);
dump_lisp_Pattern(and_pattern_p1(_node));
dump_lisp_Pattern(and_pattern_p2(_node));
      printf(")");
      break;
    case KEYchoice_pattern:
      printf("%c(choice_pattern #%d!",10,_l);
dump_lisp_Patterns(choice_pattern_choices(_node));
      printf(")");
      break;
    case KEYrest_pattern:
      printf("%c(rest_pattern #%d!",10,_l);
dump_lisp_Pattern(rest_pattern_constraint(_node));
      printf(")");
      break;
    case KEYpattern_actual:
      printf("%c(pattern_actual #%d!",10,_l);
dump_lisp_Pattern(pattern_actual_arg(_node));
dump_lisp_Expression(pattern_actual_formal(_node));
      printf(")");
      break;
    case KEYpattern_call:
      printf("%c(pattern_call #%d!",10,_l);
dump_lisp_Pattern(pattern_call_func(_node));
dump_lisp_PatternActuals(pattern_call_actuals(_node));
      printf(")");
      break;
    case KEYmatch_pattern:
      printf("%c(match_pattern #%d!",10,_l);
dump_lisp_Pattern(match_pattern_pat(_node));
dump_lisp_Type(match_pattern_type(_node));
      printf(")");
      break;
    case KEYtyped_pattern:
      printf("%c(typed_pattern #%d!",10,_l);
dump_lisp_Pattern(typed_pattern_pat(_node));
dump_lisp_Type(typed_pattern_type(_node));
      printf(")");
      break;
    case KEYno_pattern:
      printf("%c(no_pattern #%d!",10,_l);
      printf(")");
      break;
    case KEYpattern_use:
      printf("%c(pattern_use #%d!",10,_l);
dump_lisp_Use(pattern_use_use(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Module(Module _node){
  int _l = tnode_line_number(_node);
  switch (Module_KEY(_node)) {
    default: fatal_error("dump_lisp_Module crashes");
    case KEYmodule_use:
      printf("%c(module_use #%d!",10,_l);
dump_lisp_Use(module_use_use(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Class(Class _node){
  int _l = tnode_line_number(_node);
  switch (Class_KEY(_node)) {
    default: fatal_error("dump_lisp_Class crashes");
    case KEYclass_use:
      printf("%c(class_use #%d!",10,_l);
dump_lisp_Use(class_use_use(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Def(Def _node){
  int _l = tnode_line_number(_node);
  switch (Def_KEY(_node)) {
    default: fatal_error("dump_lisp_Def crashes");
    case KEYdef:
      printf("%c(def #%d!",10,_l);
dump_lisp_Symbol(def_name(_node));
dump_lisp_Boolean(def_is_constant(_node));
dump_lisp_Boolean(def_is_public(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Use(Use _node){
  int _l = tnode_line_number(_node);
  switch (Use_KEY(_node)) {
    default: fatal_error("dump_lisp_Use crashes");
    case KEYqual_use:
      printf("%c(qual_use #%d!",10,_l);
dump_lisp_Type(qual_use_from(_node));
dump_lisp_Symbol(qual_use_name(_node));
      printf(")");
      break;
    case KEYuse:
      printf("%c(use #%d!",10,_l);
dump_lisp_Symbol(use_name(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Program(Program _node){
  int _l = tnode_line_number(_node);
  switch (Program_KEY(_node)) {
    default: fatal_error("dump_lisp_Program crashes");
    case KEYprogram:
      printf("%c(program #%d!",10,_l);
dump_lisp_String(program_name(_node));
dump_lisp_Units(program_units(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Unit(Unit _node){
  int _l = tnode_line_number(_node);
  switch (Unit_KEY(_node)) {
    default: fatal_error("dump_lisp_Unit crashes");
    case KEYdecl_unit:
      printf("%c(decl_unit #%d!",10,_l);
dump_lisp_Declaration(decl_unit_decl(_node));
      printf(")");
      break;
    case KEYwith_unit:
      printf("%c(with_unit #%d!",10,_l);
dump_lisp_String(with_unit_name(_node));
      printf(")");
      break;
    case KEYno_unit:
      printf("%c(no_unit #%d!",10,_l);
      printf(")");
      break;
  }
}

void dump_lisp_Declaration(Declaration _node){
  int _l = tnode_line_number(_node);
  switch (Declaration_KEY(_node)) {
    default: fatal_error("dump_lisp_Declaration crashes");
    case KEYcase_stmt:
      printf("%c(case_stmt #%d!",10,_l);
dump_lisp_Expression(case_stmt_expr(_node));
dump_lisp_Matches(case_stmt_matchers(_node));
dump_lisp_Block(case_stmt_default(_node));
      printf(")");
      break;
    case KEYfor_stmt:
      printf("%c(for_stmt #%d!",10,_l);
dump_lisp_Expression(for_stmt_expr(_node));
dump_lisp_Matches(for_stmt_matchers(_node));
      printf(")");
      break;
    case KEYfor_in_stmt:
      printf("%c(for_in_stmt #%d!",10,_l);
dump_lisp_Declaration(for_in_stmt_formal(_node));
dump_lisp_Expression(for_in_stmt_seq(_node));
dump_lisp_Block(for_in_stmt_body(_node));
      printf(")");
      break;
    case KEYif_stmt:
      printf("%c(if_stmt #%d!",10,_l);
dump_lisp_Expression(if_stmt_cond(_node));
dump_lisp_Block(if_stmt_if_true(_node));
dump_lisp_Block(if_stmt_if_false(_node));
      printf(")");
      break;
    case KEYcollect_assign:
      printf("%c(collect_assign #%d!",10,_l);
dump_lisp_Expression(collect_assign_lhs(_node));
dump_lisp_Expression(collect_assign_rhs(_node));
      printf(")");
      break;
    case KEYnormal_assign:
      printf("%c(normal_assign #%d!",10,_l);
dump_lisp_Expression(normal_assign_lhs(_node));
dump_lisp_Expression(normal_assign_rhs(_node));
      printf(")");
      break;
    case KEYmulti_call:
      printf("%c(multi_call #%d!",10,_l);
dump_lisp_Expression(multi_call_proc(_node));
dump_lisp_Actuals(multi_call_actuals(_node));
dump_lisp_Actuals(multi_call_results(_node));
      printf(")");
      break;
    case KEYeffect:
      printf("%c(effect #%d!",10,_l);
dump_lisp_Expression(effect_e(_node));
      printf(")");
      break;
    case KEYblock_stmt:
      printf("%c(block_stmt #%d!",10,_l);
dump_lisp_Block(block_stmt_body(_node));
      printf(")");
      break;
    case KEYphylum_formal:
      printf("%c(phylum_formal #%d!",10,_l);
dump_lisp_Def(phylum_formal_def(_node));
dump_lisp_Signature(phylum_formal_sig(_node));
      printf(")");
      break;
    case KEYtype_formal:
      printf("%c(type_formal #%d!",10,_l);
dump_lisp_Def(type_formal_def(_node));
dump_lisp_Signature(type_formal_sig(_node));
      printf(")");
      break;
    case KEYseq_formal:
      printf("%c(seq_formal #%d!",10,_l);
dump_lisp_Def(seq_formal_def(_node));
dump_lisp_Type(seq_formal_type(_node));
      printf(")");
      break;
    case KEYnormal_formal:
      printf("%c(normal_formal #%d!",10,_l);
dump_lisp_Def(normal_formal_def(_node));
dump_lisp_Type(normal_formal_type(_node));
      printf(")");
      break;
    case KEYpattern_renaming:
      printf("%c(pattern_renaming #%d!",10,_l);
dump_lisp_Def(pattern_renaming_def(_node));
dump_lisp_Pattern(pattern_renaming_old(_node));
      printf(")");
      break;
    case KEYvalue_renaming:
      printf("%c(value_renaming #%d!",10,_l);
dump_lisp_Def(value_renaming_def(_node));
dump_lisp_Expression(value_renaming_old(_node));
      printf(")");
      break;
    case KEYtype_renaming:
      printf("%c(type_renaming #%d!",10,_l);
dump_lisp_Def(type_renaming_def(_node));
dump_lisp_Type(type_renaming_old(_node));
      printf(")");
      break;
    case KEYsignature_renaming:
      printf("%c(signature_renaming #%d!",10,_l);
dump_lisp_Def(signature_renaming_def(_node));
dump_lisp_Signature(signature_renaming_old(_node));
      printf(")");
      break;
    case KEYmodule_renaming:
      printf("%c(module_renaming #%d!",10,_l);
dump_lisp_Def(module_renaming_def(_node));
dump_lisp_Module(module_renaming_old(_node));
      printf(")");
      break;
    case KEYclass_renaming:
      printf("%c(class_renaming #%d!",10,_l);
dump_lisp_Def(class_renaming_def(_node));
dump_lisp_Class(class_renaming_old(_node));
      printf(")");
      break;
    case KEYpattern_replacement:
      printf("%c(pattern_replacement #%d!",10,_l);
dump_lisp_Pattern(pattern_replacement_pattern(_node));
dump_lisp_Pattern(pattern_replacement_as(_node));
      printf(")");
      break;
    case KEYvalue_replacement:
      printf("%c(value_replacement #%d!",10,_l);
dump_lisp_Expression(value_replacement_value(_node));
dump_lisp_Expression(value_replacement_as(_node));
      printf(")");
      break;
    case KEYtype_replacement:
      printf("%c(type_replacement #%d!",10,_l);
dump_lisp_Type(type_replacement_type(_node));
dump_lisp_Type(type_replacement_as(_node));
      printf(")");
      break;
    case KEYsignature_replacement:
      printf("%c(signature_replacement #%d!",10,_l);
dump_lisp_Signature(signature_replacement_sig(_node));
dump_lisp_Signature(signature_replacement_as(_node));
      printf(")");
      break;
    case KEYmodule_replacement:
      printf("%c(module_replacement #%d!",10,_l);
dump_lisp_Module(module_replacement_module(_node));
dump_lisp_Module(module_replacement_as(_node));
      printf(")");
      break;
    case KEYclass_replacement:
      printf("%c(class_replacement #%d!",10,_l);
dump_lisp_Class(class_replacement_class(_node));
dump_lisp_Class(class_replacement_as(_node));
      printf(")");
      break;
    case KEYtop_level_match:
      printf("%c(top_level_match #%d!",10,_l);
dump_lisp_Match(top_level_match_m(_node));
      printf(")");
      break;
    case KEYpragma_call:
      printf("%c(pragma_call #%d!",10,_l);
dump_lisp_Symbol(pragma_call_name(_node));
dump_lisp_Expressions(pragma_call_parameters(_node));
      printf(")");
      break;
    case KEYpolymorphic:
      printf("%c(polymorphic #%d!",10,_l);
dump_lisp_Def(polymorphic_def(_node));
dump_lisp_Declarations(polymorphic_type_formals(_node));
dump_lisp_Block(polymorphic_body(_node));
      printf(")");
      break;
    case KEYinheritance:
      printf("%c(inheritance #%d!",10,_l);
dump_lisp_Def(inheritance_def(_node));
dump_lisp_Type(inheritance_used(_node));
dump_lisp_Block(inheritance_body(_node));
      printf(")");
      break;
    case KEYpattern_decl:
      printf("%c(pattern_decl #%d!",10,_l);
dump_lisp_Def(pattern_decl_def(_node));
dump_lisp_Type(pattern_decl_type(_node));
dump_lisp_Pattern(pattern_decl_choices(_node));
      printf(")");
      break;
    case KEYconstructor_decl:
      printf("%c(constructor_decl #%d!",10,_l);
dump_lisp_Def(constructor_decl_def(_node));
dump_lisp_Type(constructor_decl_type(_node));
      printf(")");
      break;
    case KEYprocedure_decl:
      printf("%c(procedure_decl #%d!",10,_l);
dump_lisp_Def(procedure_decl_def(_node));
dump_lisp_Type(procedure_decl_type(_node));
dump_lisp_Block(procedure_decl_body(_node));
      printf(")");
      break;
    case KEYfunction_decl:
      printf("%c(function_decl #%d!",10,_l);
dump_lisp_Def(function_decl_def(_node));
dump_lisp_Type(function_decl_type(_node));
dump_lisp_Block(function_decl_body(_node));
      printf(")");
      break;
    case KEYattribute_decl:
      printf("%c(attribute_decl #%d!",10,_l);
dump_lisp_Def(attribute_decl_def(_node));
dump_lisp_Type(attribute_decl_type(_node));
dump_lisp_Direction(attribute_decl_direction(_node));
dump_lisp_Default(attribute_decl_default(_node));
      printf(")");
      break;
    case KEYvalue_decl:
      printf("%c(value_decl #%d!",10,_l);
dump_lisp_Def(value_decl_def(_node));
dump_lisp_Type(value_decl_type(_node));
dump_lisp_Direction(value_decl_direction(_node));
dump_lisp_Default(value_decl_default(_node));
      printf(")");
      break;
    case KEYtype_decl:
      printf("%c(type_decl #%d!",10,_l);
dump_lisp_Def(type_decl_def(_node));
dump_lisp_Signature(type_decl_sig(_node));
dump_lisp_Type(type_decl_type(_node));
      printf(")");
      break;
    case KEYphylum_decl:
      printf("%c(phylum_decl #%d!",10,_l);
dump_lisp_Def(phylum_decl_def(_node));
dump_lisp_Signature(phylum_decl_sig(_node));
dump_lisp_Type(phylum_decl_type(_node));
      printf(")");
      break;
    case KEYsignature_decl:
      printf("%c(signature_decl #%d!",10,_l);
dump_lisp_Def(signature_decl_def(_node));
dump_lisp_Signature(signature_decl_sig(_node));
      printf(")");
      break;
    case KEYmodule_decl:
      printf("%c(module_decl #%d!",10,_l);
dump_lisp_Def(module_decl_def(_node));
dump_lisp_Declarations(module_decl_type_formals(_node));
dump_lisp_Declarations(module_decl_value_formals(_node));
dump_lisp_Declaration(module_decl_result_type(_node));
dump_lisp_Signature(module_decl_parent(_node));
dump_lisp_Block(module_decl_contents(_node));
      printf(")");
      break;
    case KEYclass_decl:
      printf("%c(class_decl #%d!",10,_l);
dump_lisp_Def(class_decl_def(_node));
dump_lisp_Declarations(class_decl_type_formals(_node));
dump_lisp_Declaration(class_decl_result_type(_node));
dump_lisp_Signature(class_decl_parent(_node));
dump_lisp_Block(class_decl_contents(_node));
      printf(")");
      break;
    case KEYno_decl:
      printf("%c(no_decl #%d!",10,_l);
      printf(")");
      break;
  }
}

void dump_lisp_Block(Block _node){
  int _l = tnode_line_number(_node);
  switch (Block_KEY(_node)) {
    default: fatal_error("dump_lisp_Block crashes");
    case KEYblock:
      printf("%c(block #%d!",10,_l);
dump_lisp_Declarations(block_body(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Match(Match _node){
  int _l = tnode_line_number(_node);
  switch (Match_KEY(_node)) {
    default: fatal_error("dump_lisp_Match crashes");
    case KEYmatcher:
      printf("%c(matcher #%d!",10,_l);
dump_lisp_Pattern(matcher_pat(_node));
dump_lisp_Block(matcher_body(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Direction(Direction _node){
  int _l = tnode_line_number(_node);
  switch (Direction_KEY(_node)) {
    default: fatal_error("dump_lisp_Direction crashes");
    case KEYdirection:
      printf("%c(direction #%d!",10,_l);
dump_lisp_Boolean(direction_is_input(_node));
dump_lisp_Boolean(direction_is_collection(_node));
dump_lisp_Boolean(direction_is_circular(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Default(Default _node){
  int _l = tnode_line_number(_node);
  switch (Default_KEY(_node)) {
    default: fatal_error("dump_lisp_Default crashes");
    case KEYno_default:
      printf("%c(no_default #%d!",10,_l);
      printf(")");
      break;
    case KEYcomposite:
      printf("%c(composite #%d!",10,_l);
dump_lisp_Expression(composite_initial(_node));
dump_lisp_Expression(composite_combiner(_node));
      printf(")");
      break;
    case KEYsimple:
      printf("%c(simple #%d!",10,_l);
dump_lisp_Expression(simple_value(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Units(Units _node){
  int _l = tnode_line_number(_node);
  switch (Units_KEY(_node)) {
    default: fatal_error("dump_lisp_Units crashes");
    case KEYnil_Units:
      printf("%c(nil_Units #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_Units:
      printf("%c(list_Units #%d!",10,_l);
dump_lisp_Unit(list_Units_elem(_node));
      printf(")");
      break;
    case KEYappend_Units:
      printf("%c(append_Units #%d!",10,_l);
dump_lisp_Units(append_Units_l1(_node));
dump_lisp_Units(append_Units_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Declarations(Declarations _node){
  int _l = tnode_line_number(_node);
  switch (Declarations_KEY(_node)) {
    default: fatal_error("dump_lisp_Declarations crashes");
    case KEYnil_Declarations:
      printf("%c(nil_Declarations #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_Declarations:
      printf("%c(list_Declarations #%d!",10,_l);
dump_lisp_Declaration(list_Declarations_elem(_node));
      printf(")");
      break;
    case KEYappend_Declarations:
      printf("%c(append_Declarations #%d!",10,_l);
dump_lisp_Declarations(append_Declarations_l1(_node));
dump_lisp_Declarations(append_Declarations_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Matches(Matches _node){
  int _l = tnode_line_number(_node);
  switch (Matches_KEY(_node)) {
    default: fatal_error("dump_lisp_Matches crashes");
    case KEYnil_Matches:
      printf("%c(nil_Matches #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_Matches:
      printf("%c(list_Matches #%d!",10,_l);
dump_lisp_Match(list_Matches_elem(_node));
      printf(")");
      break;
    case KEYappend_Matches:
      printf("%c(append_Matches #%d!",10,_l);
dump_lisp_Matches(append_Matches_l1(_node));
dump_lisp_Matches(append_Matches_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Types(Types _node){
  int _l = tnode_line_number(_node);
  switch (Types_KEY(_node)) {
    default: fatal_error("dump_lisp_Types crashes");
    case KEYnil_Types:
      printf("%c(nil_Types #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_Types:
      printf("%c(list_Types #%d!",10,_l);
dump_lisp_Type(list_Types_elem(_node));
      printf(")");
      break;
    case KEYappend_Types:
      printf("%c(append_Types #%d!",10,_l);
dump_lisp_Types(append_Types_l1(_node));
dump_lisp_Types(append_Types_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Expressions(Expressions _node){
  int _l = tnode_line_number(_node);
  switch (Expressions_KEY(_node)) {
    default: fatal_error("dump_lisp_Expressions crashes");
    case KEYnil_Expressions:
      printf("%c(nil_Expressions #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_Expressions:
      printf("%c(list_Expressions #%d!",10,_l);
dump_lisp_Expression(list_Expressions_elem(_node));
      printf(")");
      break;
    case KEYappend_Expressions:
      printf("%c(append_Expressions #%d!",10,_l);
dump_lisp_Expressions(append_Expressions_l1(_node));
dump_lisp_Expressions(append_Expressions_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Patterns(Patterns _node){
  int _l = tnode_line_number(_node);
  switch (Patterns_KEY(_node)) {
    default: fatal_error("dump_lisp_Patterns crashes");
    case KEYnil_Patterns:
      printf("%c(nil_Patterns #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_Patterns:
      printf("%c(list_Patterns #%d!",10,_l);
dump_lisp_Pattern(list_Patterns_elem(_node));
      printf(")");
      break;
    case KEYappend_Patterns:
      printf("%c(append_Patterns #%d!",10,_l);
dump_lisp_Patterns(append_Patterns_l1(_node));
dump_lisp_Patterns(append_Patterns_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Actuals(Actuals _node){
  int _l = tnode_line_number(_node);
  switch (Actuals_KEY(_node)) {
    default: fatal_error("dump_lisp_Actuals crashes");
    case KEYnil_Actuals:
      printf("%c(nil_Actuals #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_Actuals:
      printf("%c(list_Actuals #%d!",10,_l);
dump_lisp_Expression(list_Actuals_elem(_node));
      printf(")");
      break;
    case KEYappend_Actuals:
      printf("%c(append_Actuals #%d!",10,_l);
dump_lisp_Actuals(append_Actuals_l1(_node));
dump_lisp_Actuals(append_Actuals_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_TypeActuals(TypeActuals _node){
  int _l = tnode_line_number(_node);
  switch (TypeActuals_KEY(_node)) {
    default: fatal_error("dump_lisp_TypeActuals crashes");
    case KEYnil_TypeActuals:
      printf("%c(nil_TypeActuals #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_TypeActuals:
      printf("%c(list_TypeActuals #%d!",10,_l);
dump_lisp_Type(list_TypeActuals_elem(_node));
      printf(")");
      break;
    case KEYappend_TypeActuals:
      printf("%c(append_TypeActuals #%d!",10,_l);
dump_lisp_TypeActuals(append_TypeActuals_l1(_node));
dump_lisp_TypeActuals(append_TypeActuals_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_PatternActuals(PatternActuals _node){
  int _l = tnode_line_number(_node);
  switch (PatternActuals_KEY(_node)) {
    default: fatal_error("dump_lisp_PatternActuals crashes");
    case KEYnil_PatternActuals:
      printf("%c(nil_PatternActuals #%d!",10,_l);
      printf(")");
      break;
    case KEYlist_PatternActuals:
      printf("%c(list_PatternActuals #%d!",10,_l);
dump_lisp_Pattern(list_PatternActuals_elem(_node));
      printf(")");
      break;
    case KEYappend_PatternActuals:
      printf("%c(append_PatternActuals #%d!",10,_l);
dump_lisp_PatternActuals(append_PatternActuals_l1(_node));
dump_lisp_PatternActuals(append_PatternActuals_l2(_node));
      printf(")");
      break;
  }
}

