/* Generated by a program written by John Boyland */

void dump_lisp_Signature(Signature);
void dump_lisp_Type(Type);
void dump_lisp_Expression(Expression);
void dump_lisp_Pattern(Pattern);
void dump_lisp_Module(Module);
void dump_lisp_Class(Class);
void dump_lisp_Def(Def);
void dump_lisp_Use(Use);
void dump_lisp_Program(Program);
void dump_lisp_Unit(Unit);
void dump_lisp_Declaration(Declaration);
void dump_lisp_Block(Block);
void dump_lisp_Match(Match);
void dump_lisp_Direction(Direction);
void dump_lisp_Default(Default);
void dump_lisp_Units(Units);
void dump_lisp_Declarations(Declarations);
void dump_lisp_Matches(Matches);
void dump_lisp_Types(Types);
void dump_lisp_Expressions(Expressions);
void dump_lisp_Patterns(Patterns);
void dump_lisp_Actuals(Actuals);
void dump_lisp_TypeActuals(TypeActuals);
void dump_lisp_PatternActuals(PatternActuals);
