// Generated by aps2scala version 0.3.6
import basic_implicit._;
object test_coll_implicit {
  val test_coll_loaded = true;
import tiny_implicit._;
type T_TEST_COLL[T_T] = T_T;
}
import test_coll_implicit._;

import tiny_implicit._;
trait C_TEST_COLL[T_Result, T_T] extends C_TYPE[T_Result] with C_TINY[T_Result] {
  type T_Integers;
  val t_Integers : C_TYPE[T_Integers]with C_SET[T_Integers,T_Integer];
  def v_sum : T_Integer;
  def v_leaves : T_Integers;
  val v_result : (T_Root) => T_Integer;
}

class M_TEST_COLL[T_T](name : String,val t_T : C_TYPE[T_T] with C_TINY[T_T])
  extends Module(name)
  with C_TEST_COLL[T_T,T_T]
{
  type T_Result = T_T;
  val v_equal = t_T.v_equal;
  val v_string = t_T.v_string;
  val v_assert = t_T.v_assert;
  val v_node_equivalent = t_T.v_node_equivalent;
  type T_Root = t_T.T_Root;
  val t_Root = t_T.t_Root;
  type T_Wood = t_T.T_Wood;
  val t_Wood = t_T.t_Wood;
  val p_root = t_T.p_root;
  val v_root = t_T.v_root;
  val p_branch = t_T.p_branch;
  val v_branch = t_T.v_branch;
  val p_leaf = t_T.p_leaf;
  val v_leaf = t_T.v_leaf;

  val t_Result : this.type = this;
  val t_Integers = new M_SET[T_Integer]("Integers",t_Integer);
  type T_Integers = /*TI*/T_SET[T_Integer];
  private class E_sum(anchor : Null) extends Evaluation[Null,T_Integer](anchor,"sum") with CollectionEvaluation[Null,T_Integer] {
    override def initial : T_Integer = 0;
    override def combine(v1 : T_Integer, v2 : T_Integer) = new M__basic_4[ T_Integer](t_Integer).v__op_s(v1,v2);
    override def compute : ValueType = c_sum();
  }
  private object a_sum extends E_sum(null) {}
  def v_sum:T_Integer = a_sum.get;

  private class E_leaves(anchor : Null) extends Evaluation[Null,T_Integers](anchor,"leaves") with CollectionEvaluation[Null,T_Integers] {
    override def initial : T_Integers = t_Integers.v_initial;
    override def combine(v1 : T_Integers, v2 : T_Integers) = t_Integers.v_combine(v1,v2);
    override def compute : ValueType = c_leaves();
  }
  private object a_leaves extends E_leaves(null) {}
  def v_leaves:T_Integers = a_leaves.get;

  private class E_result(anchor : T_Root) extends Evaluation[T_Root,T_Integer](anchor,anchor.toString()+"."+"result") {
    override def compute : ValueType = c_result(anchor);
  }
  private object a_result extends Attribute[T_Root,T_Integer](t_Root,t_Integer,"result") {
    override def createEvaluation(anchor : T_Root) : Evaluation[T_Root,T_Integer] = new E_result(anchor);
  }
  val v_result : T_Root => T_Integer = a_result.get _;

  def c_result(anode : T_Root) : T_Integer = {
    val anchor = anode;
    anchor match {
      case p_root(v_p,v_w) => {
        if (anode eq v_p) return v_sum;
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".result");
  }
  def c_sum() : T_Integer = {
    Debug.begin("sum");
    try {
      var collection : T_Integer = 0;
      for (anchor <- t_Result.t_Wood.nodes) anchor match {
        case p_leaf(v_l,v_x) => {
          collection = new M__basic_4[ T_Integer](t_Integer).v__op_s(collection,v_x);
        }
        case _ => {}
      }
      Debug.returns(collection.toString());
      return collection;
    } finally { Debug.end(); }
  }
  def c_leaves() : T_Integers = {
    Debug.begin("leaves");
    try {
      var collection : T_Integers = t_Integers.v_initial;
      Debug.returns(collection.toString());
      return collection;
    } finally { Debug.end(); }
  }
  override def finish() : Unit = {
    a_sum.get;
    a_leaves.get;
    a_result.finish;
    super.finish();
  }

}

